apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "externaldb"  }}
    chart: "{{ template "vehicle.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  host: {{ .Values.externalDatabase.host | b64enc | quote }}
  user: {{ .Values.externalDatabase.user | b64enc | quote }}
  database: {{ .Values.externalDatabase.database | b64enc | quote }}
  collection: {{ .Values.externalDatabase.collection | b64enc | quote }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
