apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "externaldb"  }}
    chart: "{{ template "vehicle.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  host: distric-ie289.mongodb.net/test?retryWrites=true&w=majority
  user: distric-msvc
  database: vehicle
  collection: vehicles
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
